<a href="https://colab.research.google.com/github/HaseenaB/python-coding/blob/master/Indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np


In [0]:
x=np.random.randint(12,size=(4,5))

In [0]:
x

array([[ 7,  5,  0,  3,  5],
       [ 1,  8,  2,  7,  3],
       [ 4,  0,  3,  1,  2],
       [ 8, 10,  6,  7,  9]])

In [0]:
x[2:,[1,3,2,1]]

array([[ 0,  1,  3,  0],
       [10,  7,  6, 10]])

In [0]:
y=np.random.randint(12,size=(4,5))

In [0]:
y

array([[ 6, 11,  5,  8,  4],
       [ 0,  0,  6,  5,  4],
       [10,  5, 11,  6,  9],
       [ 5,  1,  1,  0,  3]])

In [0]:
z=np.concatenate([x,y])

In [0]:
z

array([[ 7,  5,  0,  3,  5],
       [ 1,  8,  2,  7,  3],
       [ 4,  0,  3,  1,  2],
       [ 8, 10,  6,  7,  9],
       [ 6, 11,  5,  8,  4],
       [ 0,  0,  6,  5,  4],
       [10,  5, 11,  6,  9],
       [ 5,  1,  1,  0,  3]])

In [0]:
x+y

array([[13, 16,  5, 11,  9],
       [ 1,  8,  8, 12,  7],
       [14,  5, 14,  7, 11],
       [13, 11,  7,  7, 12]])

In [0]:
x-y

array([[ 1, -6, -5, -5,  1],
       [ 1,  8, -4,  2, -1],
       [-6, -5, -8, -5, -7],
       [ 3,  9,  5,  7,  6]])

In [0]:
x=np.ones((3,3))

In [0]:
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [0]:
x=np.zeros((3,3))

In [0]:
x

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [0]:
x=np.full((3,3),12)

In [0]:
x

array([[12, 12, 12],
       [12, 12, 12],
       [12, 12, 12]])

In [0]:
x=np.eye(3,3)

In [0]:
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])